function out1 = myfile(Ec_1,Ec_2,Ew_1,Ew_2,Kpump,Q1,V,Vrec,k1,k2,k3,k4,k5,k6,k7,k8,k9,k10,k11,k12,k13,k14,k15,k16,k17,k18,k19,k20,k21,k22,k23,n1,n2,n3,n4,n5,n6,n7,n8,np2,np3,np4,np5,np6,np9,pabs)
%MYFILE
%    OUT1 = MYFILE(EC_1,EC_2,EW_1,EW_2,KPUMP,Q1,V,VREC,K1,K2,K3,K4,K5,K6,K7,K8,K9,K10,K11,K12,K13,K14,K15,K16,K17,K18,K19,K20,K21,K22,K23,N1,N2,N3,N4,N5,N6,N7,N8,NP2,NP3,NP4,NP5,NP6,NP9,PABS)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Jul-2016 16:36:38

t2 = 1.0./V;
t3 = k9.*n2.*n5;
t4 = k16.*n5.*n6;
t5 = Vrec.*k17.*np3.*np5.*t2;
t6 = k10.*n1.*n4;
t7 = k22.*np3.*np9;
t8 = k3.*n1.*n8;
t9 = k23.*np4.*np9;
t10 = k2.*n1.*n8;
t11 = k4.*n1.*n8;
t12 = k14.*n6.*n8;
t13 = k12.*n6.*n8;
t14 = k13.*n6.*n8;
t15 = k21.*np6.*np9;
t16 = k6.*n1.*n8;
out1 = [t3+t4+t5+t7+t13+t15-Kpump.*n1+Q1.*t2-k1.*n1.*n8-k2.*n1.*n8-k3.*n1.*n8-k4.*n1.*n8-k5.*n1.*n8-k6.*n1.*n8-k10.*n1.*n4-k11.*n1.*n8+k20.*np2.*np9.*(1.0./2.0);-t3+t4+t5+t6+t8+t9+t10+t12+t16-Kpump.*n2+k5.*n1.*n8.*2.0-k7.*n2.*n8+k8.*n3.*n8.*2.0+k15.*n6.*n8.*2.0-k20.*np2.*np9+Vrec.*k18.*np3.*np5.*t2.*3.0+Vrec.*k19.*np4.*np5.*t2.*2.0;-t5+t6-t7+t14+k1.*n1.*n8-k8.*n3.*n8-Vrec.*k18.*np3.*np5.*t2;-t6+t8-t9+t11+k7.*n2.*n8-Vrec.*k19.*np4.*np5.*t2;-t3-t4-t5+t10+t11+t12-Vrec.*k18.*np3.*np5.*t2-Vrec.*k19.*np4.*np5.*t2;-t4-t12-t13-t14-t15-Kpump.*n6+k11.*n1.*n8-k15.*n6.*n8;t16-Kpump.*n7;pabs-Ec_1.*k1.*n1.*n8-Ec_2.*k7.*n2.*n8-Ew_1.*k22.*np3.*np9-Ew_2.*k23.*np4.*np9];
